artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Subhamdey2323/End-To-End-Face-Mask-Detection-Using-Deep-Learning/raw/refs/heads/main/FaceMask.zip?
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion